---
include:
  - board: nice_nano_v2
    shield: kilroy_dongle dongle_display
    artifact-name: kilroy_dongle_oled
  - board: nice_nano_v2
    shield: kilroy_left
  - board: nice_nano_v2
    shield: kilroy_right
  - board: nice_nano_v2
    shield: settings_reset
